getwd()
setwd("E:/Study/LPU/B.TECH/4th Year/7th Semester/INT234 - PREDICTIVE ANALYTICS/PREDICTIVE-ANALYTICS/R codes")

data <- read.csv("Datasets/student_data.csv")
View(data)
str(data)
summary(data)
??naivebayes
install.packages("e1071")
install.packages("naivebayes")
install.packages("psych")
library(naivebayes)
library(ggplot2)
library(psych)
install.packages("dplyr")
library(dplyr)
data$rank <-as.factor(data$rank)
data$admit<- as.factor(data$admit)
str(data)
xtabs(~admit+rank,data=data)
pairs.panels(data[-1])
data %>% ggplot(aes(x=admit,y=gre,fill=admit)) + geom_boxplot()+ggtitle("Box Plot")
data %>% ggplot(aes(x=gpa , fill=admit))+geom_boxplot() + ggtitle("Box Plot")

